- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"

- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "question"
  color: "d876e3"
  description: "Further information is requested"

- name: "security"
  color: "ee0701"
  description: "Security related issue"

- name: "dependencies"
  color: "0366d6"
  description: "Pull requests that update a dependency file"

- name: "performance"
  color: "16c60c"
  description: "Performance related improvements"

- name: "testing"
  color: "fbca04"
  description: "Testing related changes"

- name: "stale"
  color: "c5def5"
  description: "No recent activity"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "breaking"
  color: "b60205"
  description: "Breaking changes"

- name: "automerge"
  color: "0e8a16"
  description: "Pull requests that can be automatically merged"
