name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v9
        with:
          # Issues
          days-before-issue-stale: 60
          days-before-issue-close: 7
          stale-issue-message: "This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs."
          close-issue-message: "This issue was closed because it has been stale for 7 days with no activity."
          stale-issue-label: "stale"
          exempt-issue-labels: "pinned,security,bug,enhancement,documentation"

          # Pull Requests
          days-before-pr-stale: 30
          days-before-pr-close: 7
          stale-pr-message: "This PR has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs."
          close-pr-message: "This PR was closed because it has been stale for 7 days with no activity."
          stale-pr-label: "stale"
          exempt-pr-labels: "pinned,security,dependencies"

          # General
          exempt-all-milestones: true
          operations-per-run: 100
